import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../components/header';
import HomePlate from '../components/home-plate';
import QuestionPlate from '../components/question-plate';

const Home: NextPage = () => {
  const router = useRouter();
  const hasQuestion = !!router.query.q;
  let formattedQuestion = '';
  let answer = '';
  if (hasQuestion) {
    const question = (router.query.q as string) || 'a-b-c';
    answer = question.split('-').slice(-1)[0];
    formattedQuestion = question
      .split('-')
      .slice(0, -1)
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join(' ');
    console.log(formattedQuestion, answer);
  }

  return (
    <div>
      <Head>
        <title>Ask Samip | Answering Your Stupid Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧠</text></svg>"
        ></link>
      </Head>
      {hasQuestion && <Header />}
      <main className="h-screen flex justify-center items-center px-8 lg:px-0">
        {hasQuestion ? (
          <QuestionPlate question={formattedQuestion} answer={answer} />
        ) : (
          <HomePlate />
        )}
      </main>
    </div>
  );
};

export default Home;
